package com.example.registrox_proyecto.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.navigation.NavHostController

@Composable
fun OtpScreen(
    navController: NavHostController,
    onOtpVerified: () -> Unit
) {
    var otpGenerated by remember { mutableStateOf((100000..999999).random().toString()) }
    var otpInput by remember { mutableStateOf("") }
    var otpMessage by remember { mutableStateOf("") }

    Scaffold { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(24.dp),
            verticalArrangement = Arrangement.Center,
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Text("Verificación OTP", style = MaterialTheme.typography.headlineMedium)

            Spacer(Modifier.height(16.dp))

            OutlinedTextField(
                value = otpInput,
                onValueChange = { otpInput = it },
                label = { Text("Ingrese el código OTP") },
                modifier = Modifier.fillMaxWidth()
            )

            Spacer(Modifier.height(16.dp))

            Button(onClick = {
                if (otpInput == otpGenerated) {
                    otpMessage = "✅ Verificación exitosa"
                    onOtpVerified()
                } else {
                    otpMessage = "❌ Código incorrecto"
                }
            }) {
                Text("Verificar")
            }

            Spacer(Modifier.height(16.dp))

            Text(
                text = otpMessage,
                color = if (otpMessage.contains("✅")) MaterialTheme.colorScheme.primary
                else MaterialTheme.colorScheme.error
            )

            Spacer(Modifier.height(32.dp))

            Text("Código OTP generado: $otpGenerated", style = MaterialTheme.typography.bodySmall)
        }
    }
}
